{% set name = "tsid" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c85ce5887ced432b14c790638f3e16371c8fd245d425409f3d5951d0a564e904

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
  host:
    - python
    - eigenpy
    - libboost-python-devel
    - pinocchio
    - eiquadprog
    - urdfdom
  run:
    - python
    - eigenpy
    - pinocchio
    - eiquadprog
    - urdfdom
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
  imports:
    - tsid

about:
  home: http://github.com/stack-of-tasks/tsid
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: TSID is a C++ library for optimization-based inverse-dynamics control based on the rigid multi-body dynamics library Pinocchio.
  dev_url: https://github.com/stack-of-tasks/tsid

extra:
  recipe-maintainers:
    - EtienneAr
    - jcarpent
