{% set name = "tsid" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9f5707b61250e55c45bfde4de50fa4ce33528b06abebd1a8d18f3bc9df0613f

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - cmake
    - make  # [not win]
  host:
    - python
    - eigenpy
    - boost
    - pinocchio
    - eiquadprog
    - urdfdom
  run:
    - python
    - eigenpy
    - boost
    - pinocchio
    - eiquadprog
    - urdfdom
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
  imports:
    - tsid

about:
  home: http://github.com/stack-of-tasks/tsid
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: TSID is a C++ library for optimization-based inverse-dynamics control based on the rigid multi-body dynamics library Pinocchio.
  dev_url: https://github.com/stack-of-tasks/tsid

extra:
  recipe-maintainers:
    - EtienneAr
    - jcarpent
